config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'users/registrations' }
  root to: "home#index"
  resources :albums do
    resources :photos, only: [:new, :create, :show, :destroy]
  end
  resources :photos, only: [:index, :show, :update, :destroy]
  resource :search, only: [:show]
  get 'user/:username', to: 'users#show', as: 'user'
  get 'user/:username/:album_id', to: 'users#show_album', as: 'user_album'
  resources :subscriptions, only: [:create, :destroy]
  get 'idols', to: 'subscriptions#idols', as: 'idols'
  get 'followers', to: 'subscriptions#followers'
  resource :feeds, only: [:create, :update, :destroy]
  patch 'locale/:locale', to: 'users#change_locale', as: 'change_locale'
end

app/models/album.rb
class Album < ApplicationRecord
  enum private: { public_album: 0, private_album: 1 }
  belongs_to :user
  has_many :photos, dependent: :destroy
  has_many :feeds, dependent: :destroy

  validates :name, presence: true
  validates :private, presence: true
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :authenticate_user!
  before_action :get_album, only: %i[edit update show destroy user_album_photos]

  def index
  end

  def new
    @album = Album.new
  end

  def create
    @album = current_user.albums.create(album_params)
    if @album.errors.any?
      @errors = @album.errors.full_messages
    end
  end

  def edit
  end

  def update
    @album.name = album_params[:name]
    @album.description = album_params[:description]
    @album.private = album_params[:private]
    @album.save! if @album.changed?
  end

  def show
  end

  def destroy
    feed = @album.feeds.pluck(:id)
    ActionCable.server.broadcast(
      "feed_#{current_user.id}",
      action: :destroy,
      feed_ids: feed,
      delete_feed: true
    )
    @album.destroy
    redirect_to albums_path
  end

  private

  def album_params
    params[:album][:private] = params[:album][:private].to_i
    params[:album].permit(:name, :description, :private)
  end

  def get_album
    @album ||= current_user.albums.find(params[:id])
  end

  def user_albums
    current_user.albums.order(:id)
  end

  def user_album_photos
    @album.photos.order(created_at: :desc).page(params[:page]).per(params[:per])
  end
  helper_method :user_albums, :user_album_photos
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/_album.erb
<div class="album">
  <div class="card mb-2 box-shadow-green align-items-center">
    <a href="<%= album_path(album) %>" class="d-flex flex-column w-100 text-center">
      <%= fa_icon 'folder-open', class: 'fa-5x text-success' %>
      <span class="text-success" title="<%= album.name %>"><%= album.name %></span>
    </a>
  </div>
</div>

app/views/albums/_new.erb
<div class="container">
  <%= form_with scope: :album, url: albums_path do |f| %>
    <div class="form-group">
      <%= f.label I18n.t('.name') %>
      <%= f.text_field :name, autofocus: true, autocomplete: "name", class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label I18n.t('.description') %>
      <%= f.text_area :description, autocomplete: "description", class: 'form-control' %>
    </div>

    <div class="form-group">
      <div class="onoffswitch">
        <%= f.check_box :private, class: 'onoffswitch-checkbox', id: 'myonoffswitch' %>
        <label class="onoffswitch-label" for="myonoffswitch">
            <span class="onoffswitch-inner"></span>
            <span class="onoffswitch-switch"></span>
        </label>
      </div>
    </div>
  <% end %>
</div>

app/views/albums/create.js.erb
$('#createAlbum').on('hidden.bs.modal', function () {
  $('.modal-body').html("")
});
<% if @errors %>
  $('.modal-footer button').prop('disabled', false);
  $('#createAlbum .modal-body').append("<%= j(render 'layouts/alert', error: @errors.join(', '), pos_rel: true) %>");
  removeAlert(true);
<% else %>
  $('#createAlbum').modal('hide')
  $('.albums').append("<%= j(render 'album', album: @album) %>")
<% end %>

app/views/albums/edit.erb
<div class="container">


  <div class="d-flex align-items-center p-3 my-3 rounded box-shadow bg-light">
      <h6 class="mb-0 mr-1"><%= link_to (fa_icon 'arrow-circle-left', class: 'text-primary fa-2x', title: I18n.t('.back_to_album')), album_path(@album) %></h6>
      <h6 class="mb-0 text-primary"><%= I18n.t('.edit') %> <%= @album.name %></h6>
  </div>


  <%= form_with scope: :album, url: @album, method: :patch, remote: true do |f| %>
    <div class="d-flex flex-column align-items-center">
      <div class="d-flex w-100 justify-content-between album-edit-inputs">
        <div class="form-group rounded box-shadow bg-light text-center w-100-600">
          <%= f.label I18n.t('.name') %>
          <%= f.text_field :name, autofocus: true, autocomplete: "name", class: 'form-control' %>
        </div>

        <div class="form-group rounded">
          <div class="onoffswitch">
            <%= f.check_box :private, checked: (@album.private_album? ? true : false), class: 'onoffswitch-checkbox', id: 'myonoffswitch' %>
            <label class="onoffswitch-label" for="myonoffswitch">
              <span class="onoffswitch-inner"></span>
              <span class="onoffswitch-switch"></span>
            </label>
          </div>
        </div>
      </div>

      <div class="d-flex w-100 justify-content-between album-edit-inputs">
        <div class="form-group rounded box-shadow bg-light text-center w-100-600">
          <%= f.label I18n.t('.description') %>
          <%= f.text_area :description, autocomplete: "description", class: 'form-control' %>
        </div>

        <div class="actions">
          <%= f.submit I18n.t('.update'), class: 'btn btn-primary' %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/albums/index.erb
<div class="container-fluid h-100">
  <%= link_to (fa_icon 'plus-circle', class: 'fa-5x text-success create-new-album'), new_album_path, remote: true, data: { toogle: 'modal', target: '#createAlbum'} %>


  <div class="albums row pt-3">
    <%= render user_albums %>
  </div>
</div>


<div class="modal fade" id="createAlbum" tabindex="-1" role="dialog" aria-labelledby="createAlbumLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="createAlbumLabel"><%= I18n.t('.create_new_album') %></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal"><%= I18n.t('.close') %></button>
        <button type="button" class="btn btn-primary save-album"><%= I18n.t('.create') %></button>
      </div>
    </div>
  </div>
</div>

app/views/albums/new.erb
<div class="container">
  <%= form_with scope: :album, url: albums_path do |f| %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, autofocus: true, autocomplete: "name", class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_area :description, autocomplete: "description", class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label 'Public' %>
      <%= f.radio_button :private, :public_album, checked: true %>
      <%= f.label 'Private' %>
      <%= f.radio_button :private, :private_album %>
    </div>

    <div class="actions">
        <%= f.submit "Create", class: 'btn btn-primary' %>
      </div>
  <% end %>
</div>

app/views/albums/new.js.erb
$('#createAlbum').modal();
$('.modal-body').html("<%= j(render 'new') %>")
$('#createAlbum').on('hidden.bs.modal', function () {
  $('.modal-body').html("")
})
$('.modal-footer button').prop('disabled', false);

app/views/albums/show.erb
<div class="container-fluid h-100">
  <%= link_to (fa_icon 'plus-circle', class: 'fa-5x text-success add-new-photos'), new_album_photo_path(@album), remote: true, data: { toogle: 'modal', target: '#AddPhotos'} %>
  <div class="album-info d-flex justify-content-around align-items-center bg-secondary">
    <span class="badge badge-info"><%= @album.name %></span>
    <% if @album.description.present? %>
      <span class="btn badge badge-info" data-toggle="collapse" href="#albumDescription" role="button" aria-expanded="false" aria-controls="albumDescription"><%= I18n.t('.description') %></span>
    <% end %>
    <span><%= @album.public_album? ? (fa_icon 'unlock', class: 'text-success fa-2x', title: I18n.t('.public_album')) : (fa_icon 'lock', class: 'text-danger fa-2x', title: I18n.t('.private_album')) %></span>
    <span><%= link_to (fa_icon 'edit', class: 'text-success fa-2x'), edit_album_path(@album) %></span>
    <span class="delete-album-button"><%= link_to (fa_icon 'trash', class: 'text-danger fa-2x'), album_path(@album), method: :delete, onclick: 'showDeleteSpinner();' %></span>
    <span class="spinner" style="display:none;">
      <div class="bounce1"></div>
      <div class="bounce2"></div>
      <div class="bounce3"></div>
    </div>
  </span>

  <% if @album.description.present? %>
    <div class="collapse multi-collapse" id="albumDescription">
      <div class="card card-body">
        <%= @album.description %>
      </div>
    </div>
  <% end %>

  <div class="photos row pt-3">
    <%= render user_album_photos, from_album: true %>
  </div>
  <%= paginate user_album_photos, class: 'd-flex' %>
</div>

<div class="modal fade" id="AddPhotos" tabindex="-1" role="dialog" aria-labelledby="addPhotosLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="addPhotosLabel"><%= I18n.t('.add_photos') %></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal"><%= I18n.t('.close') %></button>
        <button type="button" class="btn btn-primary add-photos"><%= I18n.t('.add') %></button>
      </div>
    </div>
  </div>
</div>

app/views/albums/show.js.erb
$('.photos').append('<%= j(render user_album_photos, from_album: true) %>');

app/views/albums/update.js.erb
$('.err-msg').remove();
$('.content').append('<%= j(render "layouts/alert", error: I18n.t(".album_updated"), class: "success") %>');
removeAlert();