config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'users/registrations' }
  root to: "home#index"
  resources :albums do
    resources :photos, only: [:new, :create, :show, :destroy]
  end
  resources :photos, only: [:index, :show, :update, :destroy]
  resource :search, only: [:show]
  get 'user/:username', to: 'users#show', as: 'user'
  get 'user/:username/:album_id', to: 'users#show_album', as: 'user_album'
  resources :subscriptions, only: [:create, :destroy]
  get 'idols', to: 'subscriptions#idols', as: 'idols'
  get 'followers', to: 'subscriptions#followers'
  resource :feeds, only: [:create, :update, :destroy]
  patch 'locale/:locale', to: 'users#change_locale', as: 'change_locale'
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :idol, :class_name => 'User'
  belongs_to :follower, :class_name => 'User'
  validates :follower_id, uniqueness: { scope: :idol_id }
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :authenticate_user!

  def create
    return if current_user.id == params[:idol]
    @subscription = Subscription.create(idol_id: params[:idol], follower: current_user)
  end

  def destroy
    @subscription = current_user.idols.where(idol_id: params[:id]).first
    @subscription.destroy
  end

  def idols
    subscriptions = current_user.idols
    @idols = User.where(id: subscriptions.pluck(:idol_id))
  end

  def followers
    subscriptions = current_user.followers
    @followers = User.where(id: subscriptions.pluck(:follower_id))
  end
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/create.js.erb
$('#user-<%= params[:idol] %>').find('.subscription-link').html('<%= link_to I18n.t(".unfollow"), subscription_path(params[:idol]), method: :delete, remote:true %>')

app/views/subscriptions/destroy.js.erb
$('#user-<%= params[:id] %>').find('.subscription-link').html('<%= link_to I18n.t(".follow"), subscriptions_path(idol: params[:id]), method: :post, remote:true %>')

app/views/subscriptions/followers.erb
<div class="container">
  <div class="my-3 p-3 bg-white rounded box-shadow">
    <h6 class="border-bottom border-gray pb-2 mb-0"><%= I18n.t('.followers') %>:</h6>
    <% @followers.each do |user| %>
      <div class="media text-muted pt-3" id="user-<%= user.id %>">
        <div class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
          <div class="d-flex justify-content-between align-items-center w-100">
            <strong class="text-gray-dark"><%= link_to (user.user_name.present? ? "#{user.full_name} (#{user.user_name})" : user.full_name), (user.user_name.present? ? user_path(user.user_name) : user_path(user.id)) %></strong>
            <div class="subscription-link">
              <% if current_user.idol?(user.id) %>
                <%= link_to I18n.t(".unfollow"), subscription_path(user), method: :delete, remote:true %>
              <% else %>
                <%= link_to I18n.t(".follow"), subscriptions_path(idol: user), method: :post, remote:true %>
              <% end %>
            </div>
          </div>
          <% if user.user_name.present? %>
            <span class="d-block">@<%= user.user_name %></span>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/subscriptions/idols.erb
<div class="container">
  <div class="my-3 p-3 bg-white rounded box-shadow">
    <h6 class="border-bottom border-gray pb-2 mb-0"><%= I18n.t('.idols') %>:</h6>
    <% @idols.each do |user| %>
      <div class="media text-muted pt-3" id="user-<%= user.id %>">
        <div class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
          <div class="d-flex justify-content-between align-items-center w-100">
            <strong class="text-gray-dark"><%= link_to (user.user_name.present? ? "#{user.full_name} (#{user.user_name})" : user.full_name), (user.user_name.present? ? user_path(user.user_name) : user_path(user.id)) %></strong>
            <div class="subscription-link">
              <% if current_user.idol?(user.id) %>
                <%= link_to I18n.t(".unfollow"), subscription_path(user), method: :delete, remote:true %>
              <% else %>
                <%= link_to I18n.t(".follow"), subscriptions_path(idol: user), method: :post, remote:true %>
              <% end %>
            </div>
          </div>
          <% if user.user_name.present? %>
            <span class="d-block">@<%= user.user_name %></span>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>