config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'users/registrations' }
  root to: "home#index"
  resources :albums do
    resources :photos, only: [:new, :create, :show, :destroy]
  end
  resources :photos, only: [:index, :show, :update, :destroy]
  resource :search, only: [:show]
  get 'user/:username', to: 'users#show', as: 'user'
  get 'user/:username/:album_id', to: 'users#show_album', as: 'user_album'
  resources :subscriptions, only: [:create, :destroy]
  get 'idols', to: 'subscriptions#idols', as: 'idols'
  get 'followers', to: 'subscriptions#followers'
  resource :feeds, only: [:create, :update, :destroy]
  patch 'locale/:locale', to: 'users#change_locale', as: 'change_locale'
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :user
  belongs_to :album
  mount_uploader :image, ImageUploader
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :authenticate_user!
  before_action :get_album, only: %i[new create]
  before_action :get_photo, only: %i[show update destroy]

  def index
  end

  def new
    @photo = Photo.new
  end

  def create
    @photo = Photo.new(image: photo_params[:image], user_id: current_user.id, album_id: @album.id)
    if @photo.save
      @feed = current_user.feeds.where(album_id: @album.id, updated_at: 30.seconds.ago..Time.current).first
      if @feed
        update_feed(@feed, @photo.reload)
      else
        create_new_feed(@album, @photo.reload)
      end
    end
  end

  def create_new_feed(album, photo)
    @feed = current_user.feeds.create(album_id: album.id, photo_ids: [photo.id])
    val = { album: album, photos: [photo], user: current_user, feed: @feed }
    ActionCable.server.broadcast(
      "feed_#{current_user.id}",
      action: :create,
      feed: render(partial: 'feeds/feed', locals: { value: val })
    )
  end

  def update_feed(feed, photo)
    feed.photo_ids.push(photo.id)
    feed.save!
    ActionCable.server.broadcast(
      "feed_#{current_user.id}",
      action: :update,
      feed_id: feed.id,
      photos_count: feed.photo_ids.count,
      photo: render(partial: 'photos/share_photo', locals: { photo: photo, feed_id: feed.id })
    )
  end

  def show
  end

  def update
    @photo.name = photo_params[:name]
    @photo.description = photo_params[:description]
    @photo.save! if @photo.changed?
  end

  def destroy
    feed = current_user.feeds.where(album_id: @photo.album_id).where("? = ANY (photo_ids)", @photo.id).first
    if feed
      feed.photo_ids.delete(@photo.id)
      feed.save!
      if feed.photo_ids.count.zero?
        delete_feed(feed)
      else
        delete_from_feed(feed.id, @photo.id)
      end
    end
    @photo.destroy
  end

  def delete_from_feed(feed_id, photo_id)
    ActionCable.server.broadcast(
      "feed_#{current_user.id}",
      action: :destroy,
      feed_id: feed_id,
      photo_id: params[:id]
    )
  end

  def delete_feed(feed)
    ActionCable.server.broadcast(
      "feed_#{current_user.id}",
      action: :destroy,
      feed_id: feed.id,
      delete_feed: true,
      photo_id: params[:id]
    )
    feed.destroy
  end

  private

  def photo_params
    params[:photo].permit(:name, :description, :image)
  end

  def get_album
    @album ||= current_user.albums.find(params[:album_id])
  end

  def get_photo
    @photo ||= current_user.photos.find(params[:id])
  end

  def user_photos
    current_user.photos.order(created_at: :desc).page(params[:page]).per(params[:per])
  end
  helper_method :user_photos
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_caption.erb
<div>
  <p><%= I18n.t('.name') %>: <span><%= photo.name ? photo.name : I18n.t('.no_name') %></span></p>
  <p><%= I18n.t('.description') %>: <span><%= photo.description ? photo.description : I18n.t('.no_description') %></span></p>
  <% if current_user && (current_user.id == photo.user.id) && !local_assigns[:alien] %>
    <% if from_album %>
      <p><%= link_to I18n.t('.edit'), album_photo_path(album, photo, page: params[:page]), onclick: '$.fancybox.close( true );' %></p>
    <% else %>
      <p><%= link_to I18n.t('.edit'), photo_path(photo, page: params[:page]), onclick: '$.fancybox.close( true );' %></p>
    <% end %>
  <% end %>
</div>

app/views/photos/_new.erb
<div class="container">
  <%= form_with scope: :photo, url: album_photos_path(@album) do |f| %>
    <div class="form-group">
      <%= f.label I18n.t('.image') %>
      <%= f.file_field :image, multiple: true, accept: "image/*" %>
    </div>
  <% end %>
</div>
<div class="progress photo-progress" style="display: none;">
  <div class="progress-bar bg-success progress-bar-striped progress-bar-animated" role="progressbar" aria-valuemin="0" aria-valuemax="100"></div>
</div>
<div class="w-100 d-flex justify-content-around mt-2 photo-tracking" style="display: none !important;">
  <div class="photo-count"><span class="current"></span>/<span class="count"></span></div>
  <img class="photo-preview" src="#" style="height: 100px;">
</div>

app/views/photos/_photo.erb
<% if from_album %>
  <div class="photo" id="<%= photo.id %>">
    <%= link_to image_tag(photo.image_url(:thumb_150).to_s), photo.image_url.to_s, data: { fancybox: "photo", caption: (render 'photos/caption', photo: photo, album: @album, from_album: true) } %>
    <span><%= link_to (fa_icon 'trash', class: 'text-danger'), album_photo_path((@album.present? ? @album : album.id), photo), method: :delete, remote: true %> </span>
  </div>
<% else %>
  <div class="photo" id="<%= photo.id %>">
    <%= link_to image_tag(photo.image_url(:thumb_150).to_s), photo.image_url.to_s, data: { fancybox: "photo", caption: (render 'caption', photo: photo, from_album: false) } %>
    <span><%= link_to (fa_icon 'trash', class: 'text-danger'), photo_path(photo), method: :delete, remote: true %> </span>
  </div>
<% end %>

app/views/photos/_share_photo.erb
<div class="photo" id="photo-<%= photo.id %>">
  <%= link_to image_tag(photo.image_url(:thumb_150).to_s), photo.image_url.to_s, data: { fancybox: (local_assigns[:feed_id] ? local_assigns[:feed_id] : 'photo'), caption: (render 'caption', photo: photo, from_album: false, alien: true) } %>
</div>

app/views/photos/create.js.erb
$('#AddPhotos').on('hidden.bs.modal', function () {
  $('.modal-body').html("")
});

app/views/photos/destroy.js.erb
$('.photo#<%= params[:id] %>').remove();

app/views/photos/index.erb
<div class="container-fluid">
  <div class="photos row pt-3">
    <%= render user_photos, from_album: false %>
  </div>
  <%= paginate user_photos %>
</div>

app/views/photos/index.js.erb
$('.photos').append('<%= j(render user_photos, from_album: false) %>');

app/views/photos/new.erb
<div class="container">
  <%= form_with scope: :photo, url: album_photos_path(@album) do |f| %>
    <div class="form-group">
      <%= f.label :image %>
      <%= f.file_field :image, multiple: true %>
    </div>

    <div class="actions">
        <%= f.submit "Create", class: 'btn btn-primary' %>
      </div>
  <% end %>
</div>

app/views/photos/new.js.erb
$('#AddPhotos').modal();
$('.modal-body').html("<%= j(render 'new') %>")
$('#AddPhotos').on('hidden.bs.modal', function () {
  $('.modal-body').html("")
})
$('.modal-footer button').prop('disabled', false);
$('.add-photos').show();

app/views/photos/show.erb
<% if params[:album_id]%>
  <div class="d-flex align-items-center p-3 my-3 rounded box-shadow bg-light">
      <h6 class="mb-0 mr-1"><%= link_to (fa_icon 'arrow-circle-left', class: 'text-primary fa-2x', title: I18n.t('.back_to_album')), album_path(params[:album_id], page: params[:page]) %></h6>
  </div>
<% else %>
  <div class="d-flex align-items-center p-3 my-3 rounded box-shadow bg-light">
      <h6 class="mb-0 mr-1"><%= link_to (fa_icon 'arrow-circle-left', class: 'text-primary fa-2x', title: I18n.t('.back_to_photos')), photos_path(page: params[:page]) %></h6>
  </div>
<% end %>

<div class="container mt-2">
  <%= form_with scope: :photo, url: @photo, method: :patch, remote: true do |f| %>
    <div class="photo-edit d-flex align-items-center justify-content-around">
      <%= image_tag(@photo.image_url(:thumb_400).to_s, class: 'box-shadow') %>

      <div class="photo-edit-inputs flex-column">
        <div class="form-group rounded box-shadow bg-light text-center">
          <%= f.label I18n.t('.name') %>
          <%= f.text_field :name, autofocus: true, autocomplete: "name", class: 'form-control' %>
        </div>

        <div class="form-group rounded box-shadow bg-light text-center">
          <%= f.label I18n.t('.description') %>
          <%= f.text_area :description, autocomplete: "description", class: 'form-control' %>
        </div>

        <div class="actions w-25">
          <%= f.submit I18n.t('.update'), class: 'btn btn-primary' %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/photos/update.js.erb
$('.err-msg').remove();
$('.content').append('<%= j(render "layouts/alert", error: I18n.t(".photo_updated"), class: "success") %>');
removeAlert();