config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'users/registrations' }
  root to: "home#index"
  resources :albums do
    resources :photos, only: [:new, :create, :show, :destroy]
  end
  resources :photos, only: [:index, :show, :update, :destroy]
  resource :search, only: [:show]
  get 'user/:username', to: 'users#show', as: 'user'
  get 'user/:username/:album_id', to: 'users#show_album', as: 'user_album'
  resources :subscriptions, only: [:create, :destroy]
  get 'idols', to: 'subscriptions#idols', as: 'idols'
  get 'followers', to: 'subscriptions#followers'
  resource :feeds, only: [:create, :update, :destroy]
  patch 'locale/:locale', to: 'users#change_locale', as: 'change_locale'
end

app/views/layouts/_alert.erb
<div class="err-msg <%= local_assigns[:sign_up] || local_assigns[:pos_rel] ? 'position-relative' : '' %> alert alert-<%= local_assigns[:class] ? local_assigns[:class] : 'danger' %> alert-dismissible" role="alert">
  <%= error %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/layouts/_header.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to I18n.t('.home'), root_path, class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav w-100">
      <% if current_user %>
        <li class="nav-item">
          <%= link_to I18n.t('.albums'), albums_path, class: "nav-link #{'active' if current_page?(albums_path)}"  %>
        </li>
        <li class="nav-item">
          <%= link_to I18n.t('.photos'), photos_path, class: "nav-link #{'active' if current_page?(photos_path)}"  %>
        </li>
        <li class="nav-item">
          <%= link_to I18n.t('.subscriptions'), idols_path, class: "nav-link #{'active' if current_page?(idols_path)}"  %>
        </li>
        <li class="nav-item">
          <%= link_to I18n.t('.followers'), followers_path, class: "nav-link #{'active' if current_page?(followers_path)}"  %>
        </li>
        <li class="nav-item mx-auto">
          <%= render 'layouts/search_form' %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="languageDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= I18n.t('.language') %>
          </a>
          <div class="dropdown-menu" aria-labelledby="languageDropdownMenuLink">
            <%= link_to 'EN', change_locale_path(:en), method: :patch, remote: true, class: "dropdown-item #{'active' if I18n.locale == :en}" %>
            <%= link_to 'UA', change_locale_path(:uk), method: :patch, remote: true, class: "dropdown-item #{'active' if I18n.locale == :uk}" %>
          </div>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= I18n.t('logged_as', user: current_user.full_name) %>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <%= link_to I18n.t('.profile'), edit_user_registration_path, class: "dropdown-item" %>
            <%= link_to I18n.t('.log_out'), destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to I18n.t('.log_in'), new_user_session_path, class: "nav-link #{('active' if current_page?(new_user_session_path))}" %>
        </li>
        <li class="nav-item">
          <%= link_to I18n.t('.sign_up'), new_user_registration_path, class: "nav-link #{('active' if current_page?(new_user_registration_path))}" %>
        </li>
        <li class="nav-item mx-auto">
          <%= render 'layouts/search_form' %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="languageDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= I18n.t('.language') %>
          </a>
          <div class="dropdown-menu" aria-labelledby="languageDropdownMenuLink">
            <%= link_to 'EN', change_locale_path(:en), method: :patch, remote: true, class: "dropdown-item #{'active' if I18n.locale == :en}" %>
            <%= link_to 'UA', change_locale_path(:uk), method: :patch, remote: true, class: "dropdown-item #{'active' if I18n.locale == :uk}" %>
          </div>
        </li>
      <% end %>
    </ul>

  </div>
</nav>

app/views/layouts/_search_form.erb
<form class="form-inline my-2 my-lg-0" action="/search" method="get">
  <input class="form-control mr-sm-2" value="<%= params[:q] %>" name="q" type="search" placeholder="<%= I18n.t('.search_people') %>" aria-label="Search">
  <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><%= I18n.t('.search') %></button>
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Homka</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=0.5, maximum-scale=5">
  </head>

  <body>
    <div class="main">
      <div class="header">
        <%= render 'layouts/header'  %>
      </div>
      <div class="content"  <%= current_page?(root_path) && current_user ? 'onscroll=fScroll();' : '' %> >
        <% if notice %>
          <%= render 'layouts/alert', error: notice, class: 'warning' %>
        <% end %>
        <% if alert %>
          <%= render 'layouts/alert', error: alert %>
        <% end %>
        <%= yield %>
      </div>
    </div>
  </body>
</html>